### ISSUE TITLE
Not working with 3.1.0

### ISSUE THREAD

**Issue by HashandSalt** [bvdputte/kirby-fingerprint#2] opened 2019-03-21 14:12 UTC
Try as I might, I cant seem to get this work. Ive add the plugin via composer, add the .htaccess rules and im using the CSS & JS helpers as normal.

```
<?= css("assets/css/site.css") ?>
<?= js("assets/js/site.js") ?>
```

I just uploaded the site to my staging server and i just get the plain, unbusted url to the file. Any ideas?

**Comment by bvdputte** [comment] 2019-03-21 14:36
I have just tested this in a new starterkit, and in my setup it just works (without composer though)?

```
<?= css(['assets/css/index.css', '@auto']) ?>
// outputs:
// <link href="http://localhost/assets/css/index.ea0b15243b1ebacb018d4e94fb7989e9.css" rel="stylesheet">
// <link href="http://localhost/assets/css/templates/home.css" rel="stylesheet">
```
But it doesn't work as intended for `@auto` somehow 🤔.

**Comment by bvdputte** [comment] 2019-03-21 21:10
Apparently it was a composer problem that should've been fixed now. If it isn't, please let me know and I'll reopen the issue.

**Closed as completed by bvdputte** 2019-03-21 21:10 UTC
